openapi: 3.0.3
info:
  title: Inntektsmelding API
  version: 1.0.0
  description: API for håndtering av inntektsmeldinger
paths:
  /api/v1/inntektsmelding/{inntektsmeldingId}:
    get:
      summary: Hent inntektsmelding etter ID
      description: Returnerer en inntektsmelding basert på inntektsmeldingens UUID.
      parameters:
        - name: inntektsmeldingId
          in: path
          required: true
          schema:
            type: string
          description: UUID for inntektsmeldingen
      responses:
        '200':
          description: Inntektsmelding funnet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inntektsmelding'
        '404':
          description: Inntektsmelding ikke funnet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Intern serverfeil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/inntektsmelding/soek:
    post:
      summary: Søk etter inntektsmeldinger med FNR og periode
      description: Returnerer en liste over inntektsmeldinger for gitt fødselsnummer og periode.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinnInntektsmeldingerRequest'
      responses:
        '200':
          description: Liste over inntektsmeldinger
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inntektsmelding'
        '404':
          description: Ingen inntektsmeldinger funnet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Ugyldig fødselsnummer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Intern serverfeil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    FinnInntektsmeldingerRequest:
      type: object
      properties:
        fnr:
          type: string
          description: Fødselsnummer
        fom:
          type: string
          format: date
          description: Valgfri startdato
        tom:
          type: string
          format: date
          description: Valgfri sluttdato
      required:
        - fnr
    Inntektsmelding:
      type: object
      properties:
        inntektsmeldingId:
          type: string
          description: Unik ID for inntektsmeldingen
        fnr:
          type: string
          description: Fødselsnummer
        aktorId:
          type: string
          description: Aktør-ID
        uuid:
          type: string
          description: UUID for inntektsmeldingen
    Error:
      type: object
      properties:
        code:
          type: integer
          description: Feilkode
        message:
          type: string
          description: Feilmelding