logging:
    config: classpath:logback-spring.xml
management:
    endpoint:
        prometheus:
            enabled: true
    endpoints:
        web:
            base-path: /internal
            exposure:
                include: prometheus
            path-mapping:
                prometheus: /prometheus
spring:
    datasource:
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000
            maximum-pool-size: 5
        initialization-mode: never
    gammel:
        datasource:
            driverClassName: oracle.jdbc.OracleDriver
            password: ''
            url: ''
            username: ''
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
    kafka:
        bootstrap-servers: localhost:9092
    main:
        allow-bean-definition-overriding: true
        banner-mode: 'off'
srvappserver:
    password: ''
    username: srvappserver
