spring:
    flyway:
        enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    vault:
        enabled: true
        database-backend: postgresql/preprod-fss
        database-role: syfoinntektsmelding-user
        database-adminrole: syfoinntektsmelding-admin
        databaseBackend: postgresql/preprod-fss
        databaseRole: syfoinntektsmelding-user
        databaseAdminrole: syfoinntektsmelding-admin
vault:
    enabled: true
    database-backend: postgresql/preprod-fss
    database-role: syfoinntektsmelding-user
    database-adminrole: syfoinntektsmelding-admin
    databaseBackend: postgresql/preprod-fss
    databaseRole: syfoinntektsmelding-user
    databaseAdminrole: syfoinntektsmelding-admin
