networks:
  kafka-net:
    driver: bridge

services:
  spinn_db:
    build:
      context: ./
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  spinn_kafka:
    image: apache/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
