networks:
  kafka-net:
    driver: bridge

services:
  spinn_db:
    build:
      context: ./
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  spinn_zookeeper:
    image: 'bitnami/zookeeper:3.6'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  spinn_kafka:
    image: 'bitnami/kafka:2.8.0'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=spinn_zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - spinn_zookeeper
volumes:
  data:
