version: '3.4'
services:
    spinn_db:
        build:
            context: ./
        ports:
            - "5432:5432"
    spinn_kafka:
        build:
            context: ./kafka
            dockerfile: kafka.Dockerfile
        ports:
            - "2181:2181"
            - "9092:9092"
volumes:
    data:
