apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoinntektsmelding
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  ingresses:
    - https://syfoinntektsmelding.dev.intern.nav.no
    - https://syfoinntektsmelding.dev-fss-pub.nais.io
  image: {{image}}
  port: 8080
  prometheus:
    enabled: false
    path: /metrics
  liveness:
    failureThreshold: 3
    initialDelay: 60
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 3
    initialDelay: 60
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: "1024Mi"
    requests:
      cpu: "500m"
      memory: "386Mi"
  vault:
    enabled: true

  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true

  accessPolicy:
    inbound:
      rules:
        - application: helsearbeidsgiver-proxy
        - application: im-bro-spinn
          namespace: helsearbeidsgiver
          cluster: dev-gcp
  env:
    - name: KOIN_PROFILE
      value: "PREPROD"
    - name: ABAC_PDP_ENDPOINT_URL
      value: "https://wasapp-q0.adeo.no/asm-pdp/authorize"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts-q1.preprod.local/SecurityTokenServiceProvider/"
    - name: SRVSYFOINNTEKTSMELDING_USERNAME
      value: "srvsyfoinntektsmel"
    - name: OIDC_STS_ISSUERURL
      value: "http://security-token-service.default.svc.nais.local"
    - name: OIDC_STS_JWKSURL
      value: "http://security-token-service.default.svc.nais.local/rest/v1/sts/jwks"
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443"
    - name: DATABASE_HOST
      value: "b27dbvl009.preprod.local"
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "syfoinntektsmelding"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: "http://security-token-service.default.svc.nais.local/rest/v1/sts/token"
    - name: AADACCESSTOKEN_URL
      value: "https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token"
    - name: AAD_SYFOINNTEKTSMELDING_CLIENTID_USERNAME
      value: "56813e1b-97db-4da9-bcc1-a53d0a677ca2"
    - name: OPPGAVEBEHANDLING_URL
      value: "https://oppgave.nais.preprod.local/api/v1/oppgaver"
    - name: OPPRETT_SAK_URL
      value: "https://sak-q1.dev.intern.nav.no/api/v1/saker"
    - name: SRVAPPSERVER_USERNAME
      value: "srvappserver"
    - name: SRVAPPSERVER_PASSWORD
      value: ""
    - name: VAULT_BACKEND
      value: "postgresql/preprod-fss"
    - name: VAULT_MOUNTPATH
      value: "postgresql/preprod-fss/"
    - name: KAFKA_JOARK_HENDELSE_TOPIC
      value: "teamdokumenthandtering.aapen-dok-journalfoering-q1"
    - name: KAFKA_UTSATT_OPPGAVE_TOPIC
      value: "tbd.spre-oppgaver"
    - name: DOKARKIV_URL
      value: "https://dokarkiv-q1.dev.intern.nav.no/rest/journalpostapi/v1"
    - name: RUN_BACKGROUND_WORKERS
      value: "true"
    - name: PDL_URL
      value: "https://pdl-api.nais.preprod.local/graphql"
    - name: NORG2_URL
      value: "https://norg2.dev.adeo.no/norg2/api/v1"
    - name: SAF_DOKUMENT_URL
      value: "https://saf-q1.dev.intern.nav.no/rest"
    - name: SAF_JOURNAL_URL
      value: "https://saf-q1.dev.intern.nav.no/graphql"
    - name: ENHETSREGISTERET_URL
      value: "https://data.brreg.no/enhetsregisteret/api/underenheter/"
