name: Pull request

on: [pull_request]

jobs:
  Ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --console=plain build test
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: le0nidas/ktlint-pr-comments@v1.1
        with:
          repotoken: ${{ secrets.GITHUB_TOKEN }}
          arguments: "--disabled_rules=parameter-list-wrapping,final-newline"
      - uses: musichin/ktlint-check@v1
        with:
          version: '0.43.0'
