name: Slow tests

on: [pull_request]

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Build and run slowTests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --console=plain build snyk-test
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}